services:
    caddy:
        container_name: reef-caddy
        image: reef_caddy:latest
        restart: unless-stopped
        # cap_add:
        #     - NET_ADMIN
        environment:
            - "REEF_PORT=${REEF_PORT}"
            - "REEF_MANAGER_HOST=reef-manager"
            - "REEF_MANAGER_PORT=${REEF_MANAGER_PORT}"
        ports:
            - "${PORT}:${REEF_PORT}"
        depends_on:
            - manager

    compiler:
        container_name: reef-compiler
        image: reef_compiler:latest
        restart: unless-stopped
        environment:
            - "REEF_COMPILER_PORT=${REEF_COMPILER_PORT}"

    db:
        container_name: reef-db
        image: postgres:14.1-alpine
        restart: unless-stopped
        volumes:
            - reef-db-data:/var/lib/postgresql/data
            - /etc/localtime:/etc/localtime:ro
        environment:
            - "POSTGRES_USER=${REEF_DB_USERNAME}"
            - "POSTGRES_PASSWORD=${REEF_DB_PASSWORD}"
            - "POSTGRES_DB=${REEF_DB_NAME}"

    manager:
        container_name: reef-manager
        image: reef_manager:latest
        restart: unless-stopped
        volumes:
            - "reef-cache-data:/${REEF_COMPILER_CACHE_PATH}"
            - "reef-dataset-data:/${REEF_DATASETS_PATH}"
        environment:
            - "REEF_MANAGER_PORT=${REEF_MANAGER_PORT}"
            - "REEF_LOG_LEVEL=${REEF_LOG_LEVEL}"
            - "REEF_ADMIN_TOKEN=secret"

            - "REEF_TEMPLATES_PATH=${REEF_TEMPLATES_PATH}"
            - "REEF_DATASETS_PATH=${REEF_DATASETS_PATH}"
            - "REEF_COMPILER_CACHE_PATH=${REEF_COMPILER_CACHE_PATH}"

            - "REEF_COMPILER_IP=reef-compiler"
            - "REEF_COMPILER_PORT=${REEF_COMPILER_PORT}"

            - "REEF_DB_USERNAME=${REEF_DB_USERNAME}"
            - "REEF_DB_PASSWORD=${REEF_DB_PASSWORD}"
            - "REEF_DB_NAME=${REEF_DB_NAME}"
            - "REEF_DB_HOST=reef-db"
            - "REEF_DB_PORT=${REEF_DB_PORT}"
        depends_on:
            - compiler
            - db

volumes:
    reef-db-data:
    reef-cache-data:
    reef-dataset-data:
