[package]
name = "reef_protocol_compiler"
version.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
capnp.workspace = true

[build-dependencies]
capnpc.workspace = true
