[package]
name = "reef_protocol_compiler"
version.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
capnp = "0.19.5"

[build-dependencies]
capnpc = "0.19"
