//
// Reef data / schema definition file for job logs.
//

export enum ILogKind {
  // Logs that the program generates,
  // be it a print-like function or a panic message.
  LogKindProgram,
  // Logs generated by the worker node,
  // often related to networking or debugging.
  LogKindNode,
  // Logs generated by the manager / system.
  // Also often related to networking or debugging.
  LogKindSystem,
}

export interface ILogEntry {
  // Logs can be filtered based on their kind.
  // As a default, only the `program` kind is shown.
  // The user can use a dropdown / checkbox to select kinds to be shown.
  kind: ILogKind;
  // RFC 3339 time format with sub-second precision.
  created: string;
  // UTF-8 encoded log content.
  content: string;
  // Foreign key: stores the job-id of the job which produced that log entry.
  // The backend guarantees that this job-id always refers to an existent job.
  jobId: string;
}
