[package]
name = "placeholder"
version = "0.1.0"
edition = "2021"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
#! CHORE: update Cargo.lock when adding deps
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
csv = "1.3.0"
