[package]
name = "reef_wasm_interface"
version.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
reef_interpreter.workspace = true
reef_protocol_node.workspace = true
